name: Build Rage Edition

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-android64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract mod project
        run: |
          unzip -o RageEditionGeodeMod.zip -d extracted
          find extracted -type f
          cd extracted/RageEditionGeodeMod
          echo "PROJECT_DIR=$PWD" >> $GITHUB_ENV

      - name: Build Android64 .geode
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          sdk: latest
          cli: latest

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: RageEdition-Android64
          path: ${{ steps.build.outputs.build-output }}
